postgres:
  url: "jdbc:postgresql://localhost:5432/lendloop"
  user: "postgres"
  password: "postgres"
ktor:
  deployment:
    port: 8080
  application:
    modules:
      - nexus.HttpKt.configureHttp
      - nexus.SerializationKt.configureSerialization
      - nexus.PostgresKt.configurePostgres
      - nexus.RpcKt.configureRpc
      - nexus.ResourcesKt.configureResources
      - nexus.RoutingKt.configureRouting
